### ISSUE TITLE
Errors when trying to compile.

### ISSUE THREAD

**Issue by Fro5ty** [oscar-broman/samp-weapon-config#99]
I am using the newest release and the newest SKY plugin release. I included weapon-config in my gamemode. I do not use any filterscripts. 

Server Version: 0.3.DL

```
weapon-config.inc(1530) : error 035: argument type mismatch (argument 2)
weapon-config.inc(1917) : error 035: argument type mismatch (argument 4)
weapon-config.inc(3728) : warning 202: number of arguments does not match definition
weapon-config.inc(3728) : warning 202: number of arguments does not match definition
weapon-config.inc(3728) : warning 202: number of arguments does not match definition
weapon-config.inc(4049) : error 021: symbol already defined: "IsPlayerPaused"
weapon-config.inc(4896) : error 035: argument type mismatch (argument 2)
weapon-config.inc(5777) : error 025: function heading differs from prototype
weapon-config.inc(5897) : warning 201: redefinition of constant/macro (symbol "SetPlayerHealth")
weapon-config.inc(5921) : warning 201: redefinition of constant/macro (symbol "SetPlayerArmour")
```
The .inc: (Same as latest release)
https://pastebin.com/n6auM2U4

**Comment by ADRFranklin** [comment]
You may need to update your `a_samp` include file, it seems you might have outdated callbacks.

As for the rest, it seems you have similar functions, or you have a problem with your code causing a pile up of irrelevant code. Normally happens when you miss a semi-colon, braces, or forget to close a string.

If you could give me more information, I would be happy to help you out.

**Comment by ADRFranklin** [comment]
Actually I reviewed the code, and found the problem that you are facing, I have updated the code to reflect better changes.

**Comment by Fro5ty** [comment]
The update fixed the two warnings I had and the IsPlayerPaused error, however the other errors are still there. I have replaced all of my samp includes with the newest ones from the SA-MP 0.3.DL server package.  My actual gamemode compiles fine without any errors when I'm not using the include so I don't have any code that is missing semi-colons, braces, or quotation marks.

weapon-config.inc(1530) : error 035: argument type mismatch (argument 2)
weapon-config.inc(1917) : error 035: argument type mismatch (argument 4)
weapon-config.inc(3728) : warning 202: number of arguments does not match definition
weapon-config.inc(3728) : warning 202: number of arguments does not match definition
weapon-config.inc(3728) : warning 202: number of arguments does not match definition
weapon-config.inc(5777) : error 025: function heading differs from prototype

**Comment by ADRFranklin** [comment]
I have this working on 4 of my servers all uses different libraries. I am not able to re-create these errors. I have a feeling if you re-order your includes, the errors might go away.

**Comment by ADRFranklin** [comment]
Okay I have reverted the const correctness for now. However please update your script in the future to use the new standard library: https://github.com/sampctl/samp-stdlib

This enforces const correctness, which is what is now expected.

**Comment by Fro5ty** [comment]
https://github.com/sampctl/samp-stdlib

That is for 0.3.7 but I am using 0.3.DL

**Comment by ADRFranklin** [comment]
If you checked the release page, you would of seen: https://github.com/sampctl/samp-stdlib/releases/tag/0.3.DL-R1

**Comment by Y-Less** [comment]
would have*

**Comment by Fro5ty** [comment]
I used the 0.3.DL stdlib that you linked and it made every single include that I use return errors. The 0.3.DL server package from the SA-MP website doesn't do this

**Comment by ADRFranklin** [comment]
That's cause the one provided by SA-MP, is lacking consistency. It doesn't properly use const correctness and tags are not correctly enforced. 

Please follow the new one, as it's the proper way to do it.

**Comment by Fro5ty** [comment]
I can't use the new one. If I use the new one I can't use any includes

**Comment by ADRFranklin** [comment]
Then you are going to have to redefine the definitions to work with weapon-config. 
There is really no other way
